local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5 
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 7 
  height: 7
  resolution: 0.03 